{
 "title": "Monitor - Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "query": "label_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Consul Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=~\"/tmp/consul-agent\\\\.log|/tmp/consul-server\\\\.log\", host=~\"$Host\"} | host  =~ `$Host`"
    }
   ]
  },
  {
   "title": "Envoy sidecars",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{filename=~\"/tmp/sidecar-proxy\\\\.log\"} | host  =~ `$Host`"
    }
   ]
  },
  {
   "title": "Grafan Agent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{filename=~\"/tmp/grafana-agent\\\\.log\"} | host  =~ `$Host`"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{filename=~\"/tmp/payments\\\\.log|/tmp/frontend\\\\.log|/tmp/product_api\\\\.log|/tmp/public_api\\\\.log|/tmp/database\\\\.log\"} | host  =~ `$Host`"
    }
   ]
  }
 ]
}